export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: '邮箱或密码错误',
  USER_NOT_FOUND: '用户不存在',
  EMAIL_EXISTS: '邮箱已被注册',
  USERNAME_EXISTS: '用户名已被使用',
  INVALID_TOKEN: '无效的令牌',
  TOKEN_EXPIRED: '令牌已过期',
  ACCOUNT_LOCKED: '账号已被锁定，请15分钟后再试',
  RATE_LIMIT_EXCEEDED: '请求过于频繁，请稍后再试',
  SERVER_ERROR: '服务器内部错误',
} as const;

export const ACHIEVEMENTS = [
  {
    code: 'FIRST_LOGIN',
    name: '初次登录',
    description: '完成首次登录',
    icon: '🎯',
    points: 10,
    condition: (data: any) => data.loginCount >= 1,
  },
  {
    code: 'LOGIN_STREAK_7',
    name: '连续登录7天',
    description: '连续登录7天',
    icon: '🔥',
    points: 50,
    condition: (data: any) => data.loginStreak >= 7,
  },
  {
    code: 'LOGIN_STREAK_30',
    name: '连续登录30天',
    description: '连续登录30天',
    icon: '🔥',
    points: 200,
    condition: (data: any) => data.loginStreak >= 30,
  },
  {
    code: 'SECURITY_MASTER',
    name: '安全大师',
    description: '启用MFA和生物识别',
    icon: '🛡️',
    points: 100,
    condition: (data: any) => data.mfaEnabled && data.biometricEnabled,
  },
  {
    code: 'DEVICE_COLLECTOR',
    name: '设备收藏家',
    description: '在3个不同设备上登录',
    icon: '📱',
    points: 30,
    condition: (data: any) => data.deviceCount >= 3,
  },
  {
    code: 'NIGHT_OWL',
    name: '夜猫子',
    description: '在凌晨1-5点登录',
    icon: '🦉',
    points: 20,
    condition: (data: any) => data.nightLogin,
  },
  {
    code: 'EARLY_BIRD',
    name: '早起的鸟儿',
    description: '在早上5-7点登录',
    icon: '🐦',
    points: 20,
    condition: (data: any) => data.earlyLogin,
  },
  {
    code: 'PASSWORD_GUARDIAN',
    name: '密码守护者',
    description: '使用强密码',
    icon: '🔐',
    points: 30,
    condition: (data: any) => data.strongPassword,
  },
  {
    code: 'MFA_PIONEER',
    name: 'MFA先锋',
    description: '启用双因素认证',
    icon: '🔒',
    points: 50,
    condition: (data: any) => data.mfaEnabled,
  },
  {
    code: 'BIOMETRIC_PIONEER',
    name: '生物识别先驱',
    description: '启用生物识别登录',
    icon: '👆',
    points: 50,
    condition: (data: any) => data.biometricEnabled,
  },
] as const;
